Support python 3.10
ablab/spades pull request #914
Opened 2022-02-10 16:37 UTC by AlexGhiti

distutils is deprecated and its use triggers DeprecationWarning which
make some Ubuntu autopkgtests fail: fix this by replacing distutils by
equivalent functions.

distutils.version is simply replaced with packaging.version.

distutils.copy_tree is a bit more complicated as preserve_mode/times
does not exist directly in shutil.copytree function.

Signed-off-by: Alexandre Ghiti <alexandre.ghiti@canonical.com>

2022-03-14 18:13 UTC, olga24912 requested changes

2022-03-14 18:13 UTC, olga24912 commented on assembler/src/spades_pipeline/support.py
> +except ModuleNotFoundError:
(we support 2.7, 3.6-3.10)
Supported only since 3.6 

Better use: ImportError

2022-03-14 18:13 UTC, olga24912 commented on assembler/src/spades_pipeline/stages/stage.py
> +        shutil.copytree(src, dst, copy_function = copy_fn, dirs_exist_ok = True)
(we support 2.7, 3.6-3.10)
dirs_exist_ok is supported only since 3.8
copy_function is supported only since 3.2

none of this is supported in 2.7

2022-03-14 18:29 UTC, olga24912 commented
Hi @AlexGhiti ! 

Thank you for your PR and for your help in making SPAdes better! 

The main problem with current changes is that we support not only python 3.10, but also 2.7, 3.6-3.10. I have already made some fixes in our developer repo, but I don't like how they look. Maybe you have some better solutions for the issues which I pointed out in the comments in this PR. 

We will fix the issue with python 3.10 in the next release :) 

Best regards, 
Olga

2023-07-10 02:38 UTC, asl commented
Obsolete

2023-07-10 02:38 UTC, closed without merging